#!/bin/bash

lsof -n -P -iTCP -sTCP:LISTEN -F 'cpRutn' | awk '
  BEGIN { printf "%-20s %-7s %-7s %-10s %-8s %s\n", "COMMAND", "PID", "PPID", "USER", "TYPE", "Port Usage" }
  /^p/ {pid=substr($0,2)}
  /^R/ {ppid=substr($0,2)}
  /^c/ {cmd=substr($0,2)}
  /^u/ {usr=substr($0,2)}
  /^t/ {typ=substr($0,2)}
  /^n/ {printf "%-20s %-7s %-7s %-10s %-8s %s\n", cmd, pid, ppid, usr, typ, substr($0,2)}
' | fzf-pop --multi --header-lines=1 --ansi --prompt="KILL> " | awk '{print $2}' | xargs kill
